---
author: Alvarez Ignacio Nicolas y ::::::::
title: "Analisis exploratorio de dataSet 'House-Pricing'"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Carga de Librerias
```{r Librerías}
library("dplyr")
library("corrplot")
library("fastDummies")
library("ggplot2")
library("rpart")
library("rpart.plot")
library("caret")
library("caTools")
library("randomForest")
library("class")
```
### Establecimiento del entorno de trabajo
```{r Librerías}
#setwd("~/R-WORKSPACE/Parcial2/parcial-datamining/")
```

```{r Librerías}
setwd("C:/R/house-pricing/parcial-datamining")
```

###Cargar del DataSet
```{r Librerías}

raw_data <- read.csv("house_data.csv")
```

###Graficos de Dispersión
```{r Librerías}

plot(price~., data=raw_data,col="blue")
```

### Estructura del DataSet
```{r Librerías}
str(raw_data)
```

### Descripcion del DataSet
```{r}
summary(raw_data)
```

### BoxPlot

```{r}
par(mfrow = c(1,3))
boxplot(raw_data$price, main="Price")
boxplot(raw_data$bedrooms, main="Cant Bedrooms")
boxplot(raw_data$bathrooms, main="Cant Bathrooms")
```

```{r}
par(mfrow = c(1,4))
boxplot(raw_data$sqft_living, main="sqft_living (ft^2)")
boxplot(raw_data$sqft_living15, main="sqft_living15 (ft^2)")
```

```{r}
par(mfrow = c(1,2))
boxplot(raw_data$sqft_lot, main="sqft_lot (ft^2)")
boxplot(raw_data$sqft_lot15, main="sqft_lot15 (ft^2)")
```


```{r}
par(mfrow = c(1,3))
boxplot(raw_data$sqft_above, main="sqft_above (ft^2)")
boxplot(raw_data$sqft_basement, main="sqft_basement (ft^2)")
boxplot(raw_data$condition, main="condition")
```



```{r Librerías}
df_sqft = select(raw_data, sqft_living, sqft_lot, sqft_above, sqft_living15, sqft_lot15, sqft_basement)

corrplot(cor(df_sqft),method="square")

cor(df_sqft)

```




```{r Librerías}

prueba= raw_data

prueba = mutate(prueba,sqft_living.nuevo=raw_data$sqft_above/raw_data$sqft_living)

prueba = mutate(prueba,sqft_basement.nuevo=ifelse(raw_data$sqft_basement>0,raw_data$sqft_above/raw_data$sqft_basement,0))

prueba = mutate(prueba,sqft_lot15.nuevo=(raw_data$sqft_lot-raw_data$sqft_lot15)/raw_data$sqft_lot)

prueba = mutate(prueba,sqft_living15.nuevo=(raw_data$sqft_living-raw_data$sqft_living15)/raw_data$sqft_living)

#prueba$sqft_living=raw_data$sqft_above/raw_data$sqft_living
#prueba$sqft_basement=raw_data$sqft_above/raw_data$sqft_basement
head(prueba)
summary(prueba)

corrplot(cor(prueba[,c("sqft_living.nuevo","sqft_lot","sqft_above","sqft_living15.nuevo","sqft_lot15.nuevo","sqft_basement.nuevo")]),method="square")

cor(prueba[,c("sqft_living.nuevo","sqft_lot","sqft_above","sqft_living15.nuevo","sqft_lot15.nuevo","sqft_basement.nuevo")])

```



```{r Librerías}
plot(prueba$price~prueba$sqft_living.nuevo)
```


#Analisis de los datos de la renovacion para ver el rango de valores que abarca sin utilizar las que tienen cero, quiero ver si se podria discretisarlos y expresarla como factor en "No renovada", "1991","1992", etc.
```{r Librerías}
#Aca voy a relacionar el año de renovacion y de construccion para ver la correlacion
corrplot(cor(raw_data[,c("yr_renovated","yr_built")]),method="square")

renovacion= filter(raw_data,yr_renovated>0)
#observaciones 914

renovacion2= filter(raw_data,yr_renovated>=yr_built)
#observaciones 914
#por lo tanto los datos de yr renovacion y built tienen sentido por que las que tienen renovacion son posteriores a los de construccion


par(mfrow = c(1,3))
boxplot(renovacion$yr_renovated, main="Renovated")$stats
boxplot(renovacion$yr_built, main="Built")$stats
#Built esta bastante bien a mi parecer, luego renovacion tiene muchos outliners

renovacion= filter(renovacion,yr_renovated>1957)
#Nos quito unas observacioens insignificantes asi que podria ser factible este filtro

par(mfrow = c(1,3))

boxplot(renovacion$yr_renovated, main="Renovated Desdepues del filtro")$stats

summary(renovacion$yr_renovated)

plot(renovacion$price~renovacion$yr_renovated)
```



```{r Librerías}
raw_data=mutate(raw_data, yr_renovated.nuevo=ifelse(yr_renovated==0,"NoRenovado",ifelse(yr_renovated>1957,"renovado","quitar")))
raw_data=filter(raw_data,yr_renovated.nuevo!="quitar")
raw_data$yr_renovated.nuevo=as.factor(raw_data$yr_renovated.nuevo)


par(mfrow = c(1,2))
pie(summary(as.factor(raw_data$yr_renovated.nuevo)), labels = c("No_renovado","renovado"), main = "Distribución de 'Renovacion'")

plot(raw_data$price~raw_data$yr_renovated.nuevo)

raw_data <- dummy_cols(raw_data, select_columns = c("yr_renovated.nuevo"))
raw_data$yr_renovated.nuevo <- NULL
corrplot(cor(raw_data[,c("yr_renovated.nuevo_renovado","yr_renovated.nuevo_NoRenovado","price")]),method="square")
cor(raw_data[,c("yr_renovated.nuevo_renovado","yr_renovated.nuevo_NoRenovado","price")])
```